server:
  port: 9527

spring:
  application:
    name: micro-service-cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: micro-service-cloud-dept
  prefix: /ityang
  ignored-services: "*"
  routes:
    mydept.serviceId: micro-service-cloud-dept
    mydept.path: /mydept/**

info:
  app.name: ityang-micro-cloud
  company.name: www.ityang.com
  build.artifactId: micro-service-cloud-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT



























































